/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.demo.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TeacherKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6594275608276748218L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TeacherKey\",\"namespace\":\"com.example.demo.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"subjectName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TeacherKey> ENCODER =
      new BinaryMessageEncoder<TeacherKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TeacherKey> DECODER =
      new BinaryMessageDecoder<TeacherKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TeacherKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TeacherKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TeacherKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TeacherKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TeacherKey from a ByteBuffer. */
  public static TeacherKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int id;
  @Deprecated public java.lang.CharSequence subjectName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TeacherKey() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param subjectName The new value for subjectName
   */
  public TeacherKey(java.lang.Integer id, java.lang.CharSequence subjectName) {
    this.id = id;
    this.subjectName = subjectName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return subjectName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: subjectName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'subjectName' field.
   * @return The value of the 'subjectName' field.
   */
  public java.lang.CharSequence getSubjectName() {
    return subjectName;
  }

  /**
   * Sets the value of the 'subjectName' field.
   * @param value the value to set.
   */
  public void setSubjectName(java.lang.CharSequence value) {
    this.subjectName = value;
  }

  /**
   * Creates a new TeacherKey RecordBuilder.
   * @return A new TeacherKey RecordBuilder
   */
  public static com.example.demo.schema.TeacherKey.Builder newBuilder() {
    return new com.example.demo.schema.TeacherKey.Builder();
  }

  /**
   * Creates a new TeacherKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TeacherKey RecordBuilder
   */
  public static com.example.demo.schema.TeacherKey.Builder newBuilder(com.example.demo.schema.TeacherKey.Builder other) {
    return new com.example.demo.schema.TeacherKey.Builder(other);
  }

  /**
   * Creates a new TeacherKey RecordBuilder by copying an existing TeacherKey instance.
   * @param other The existing instance to copy.
   * @return A new TeacherKey RecordBuilder
   */
  public static com.example.demo.schema.TeacherKey.Builder newBuilder(com.example.demo.schema.TeacherKey other) {
    return new com.example.demo.schema.TeacherKey.Builder(other);
  }

  /**
   * RecordBuilder for TeacherKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TeacherKey>
    implements org.apache.avro.data.RecordBuilder<TeacherKey> {

    private int id;
    private java.lang.CharSequence subjectName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.demo.schema.TeacherKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subjectName)) {
        this.subjectName = data().deepCopy(fields()[1].schema(), other.subjectName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TeacherKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.demo.schema.TeacherKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subjectName)) {
        this.subjectName = data().deepCopy(fields()[1].schema(), other.subjectName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Integer getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.example.demo.schema.TeacherKey.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.example.demo.schema.TeacherKey.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'subjectName' field.
      * @return The value.
      */
    public java.lang.CharSequence getSubjectName() {
      return subjectName;
    }

    /**
      * Sets the value of the 'subjectName' field.
      * @param value The value of 'subjectName'.
      * @return This builder.
      */
    public com.example.demo.schema.TeacherKey.Builder setSubjectName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.subjectName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'subjectName' field has been set.
      * @return True if the 'subjectName' field has been set, false otherwise.
      */
    public boolean hasSubjectName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'subjectName' field.
      * @return This builder.
      */
    public com.example.demo.schema.TeacherKey.Builder clearSubjectName() {
      subjectName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TeacherKey build() {
      try {
        TeacherKey record = new TeacherKey();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.subjectName = fieldSetFlags()[1] ? this.subjectName : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TeacherKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<TeacherKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TeacherKey>
    READER$ = (org.apache.avro.io.DatumReader<TeacherKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
